language: python
python:
  - '2.7'
branches:
  only:
  - source
install: 
  - pip install -r requirements.txt
  - pip install git+https://github.com/fuzzmz/pelicanfly@font-awesome-4.3.0
script:
  - make publish
  - make github
env:
  global:
  - secure: M88dgw5e8vf2W9wXgTJCxPsFfQSjkXeHrPfiyllyd7ypPY0AynIbsLGlvS0d6ZKPlXgHNaVQqRcvGSvobLb5FuADyamvPKNLf+LmUOuRh0aiK91s+kVo9+qobl9a4kgY2n5flbZpWAyOYDlMdwZHl9B9uBK1i5KtZMT1j+FKAEk=
