language: python
python:
- '2.7'
branches:
  only: source
install: pip install -r requirements.txt
script:
- make publish
- 'make github 2> /dev/null'
env:
  global:
  - secure: hMNTFmVyu6z0HbkjjNc3URaNuMJwXXAgQy/A0aKZxkCZD4zl8XY0jOzLmKMZXLK/jvpVS11TthrUgoXKWeOTVv/Q3dtXbZb0U9XH0N8JplNJvikuh6ywa6RBsMIm2pH2JIh05F3e0rT3TVwyC8mpMe2+3MDvbs5EHjySzovuZq8=
